production:
  solr:
    memory: 256M
    hostname: localhost
    port: 8983
    log_level: WARNING
    path: /solr/default
    # read_timeout: 2
    # open_timeout: 0.5

staging:
  solr:
    memory: 256M
    hostname: localhost
    port: 8983
    log_level: WARNING
    path: /solr/default
    # read_timeout: 2
    # open_timeout: 0.5

development:
  solr:
    memory: 256M
    hostname: localhost
    port: 8982
    log_level: INFO
    path: /solr/development

test:
  solr:
    memory: 256M
    hostname: localhost
    port: 8982
    log_level: WARNING
    path: /solr/development
    
